responsive design done
wolox-training/jl-angular pull request #11
Opened 2020-03-03 13:09 UTC by jersonlopez

## Summary
- responsive design added to book detail using sass variables

## Screenshot
![image](https://user-images.githubusercontent.com/17531513/75778577-11620b80-5d26-11ea-96ac-7074c33054d0.png)

## Trello Card
https://trello.com/c/zMIYJjpr/34-responsive

2020-03-03 20:01 UTC, CrisVega08 requested changes

2020-03-03 20:01 UTC, CrisVega08 commented on maquetado/scss/detail.scss
> +  .body {
Try to avoid styles on tags

2020-03-03 20:01 UTC, CrisVega08 commented on maquetado/scss/detail.scss
> +    max-height: 100%;
max-height and max-width , try to use a exact value for example 

`max-width: 300px;
width: 100%;`

2020-03-03 20:01 UTC, CrisVega08 commented on maquetado/scss/detail.scss
> +$badge-width: 80px;
Add empty line and define these in top file

2020-03-03 20:01 UTC, CrisVega08 commented on maquetado/scss/detail.scss
> +      height: calc(#{$badge-height} - #{$badge-height} * 0.3);
jejeje nice

2020-03-04 21:36 UTC, jersonlopez commented on maquetado/scss/detail.scss
> +  .body {
keep calm bro, this is a class not a tag

2020-05-20 13:20 UTC, CrisVega08 commented on maquetado/scss/detail.scss
> +    padding-bottom: 10px;
you can add this style of book-description at line 137 using ampersand character.
```
.class {
  ...
  &:pseudo-class{ }
}
```

2020-05-20 13:20 UTC, CrisVega08 commented on maquetado/scss/detail.scss
> +  .body {
jajaja you're right change this name please.

2020-05-20 13:20 UTC, CrisVega08 commented on maquetado/scss/detail.scss
> +@media only screen and (max-width: 1024px) {
Use a variable for 1024px; you can create other partial fiel for example _sizes.scss like _colors.scss

2020-05-20 13:20 UTC, CrisVega08 commented on maquetado/scss/detail.scss
> +$badge-height: 95px;
You can move these definitions to a partial file.

2020-06-11 16:21 UTC, CrisVega08 approved these changes

2020-06-19 01:52 UTC, merged